### ISSUE TITLE
InstaScale pod in a CrashLoopBackOff after submitting a sample appwrapper

### ISSUE THREAD

**Issue by jbusche** [project-codeflare/instascale#39]
I noticed that when I submit a sample appwrapper, that it's causing a CrashLoopBackOff of the Instascale pod.
```
oc get pods -n opendatahub |grep insta
instascale-instascale-6bb58b6559-m8snx                 0/1     CrashLoopBackOff   62 (2m20s ago)   16h
```
And in the log I see:
```
I0322 18:03:14.944406       1 appwrapper_controller.go:409] Pending AppWrapper defaultaw-schd-spec-with-timeout-104 needs scaling
E0322 18:03:14.944519       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 348 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1641a80?, 0xc000b4db78})
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/runtime/runtime.go:74 +0x86
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x415ed0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1641a80, 0xc000b4db78})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/project-codeflare/instascale/controllers.discoverInstanceTypes(0xc000e98c00)
	/workspace/controllers/appwrapper_controller.go:287 +0x265
github.com/project-codeflare/instascale/controllers.onUpdate({0x14f0360?, 0xc000e5d8f0?}, {0x16ed9c0?, 0xc000e98c00?})
	/workspace/controllers/appwrapper_controller.go:262 +0x17c
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/controller.go:238
k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnUpdate({0x18081e0?, {0x1958fa0?, 0xc0009e8918?}}, {0x16ed9c0, 0xc000dd2c00}, {0x16ed9c0, 0xc000e98c00})
	/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/controller.go:273 +0xe2
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/shared_informer.go:785 +0xf7
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0000b6f38?, {0x1944860, 0xc0005a6030}, 0x1, 0xc000a7a060)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x31?, 0xc0000b6fb0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000206300)
	/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/shared_informer.go:781 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:71 +0x85
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 348 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x415ed0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/runtime/runtime.go:55 +0xd7
panic({0x1641a80, 0xc000b4db78})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/project-codeflare/instascale/controllers.discoverInstanceTypes(0xc000e98c00)
	/workspace/controllers/appwrapper_controller.go:287 +0x265
github.com/project-codeflare/instascale/controllers.onUpdate({0x14f0360?, 0xc000e5d8f0?}, {0x16ed9c0?, 0xc000e98c00?})
	/workspace/controllers/appwrapper_controller.go:262 +0x17c
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/controller.go:238
k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnUpdate({0x18081e0?, {0x1958fa0?, 0xc0009e8918?}}, {0x16ed9c0, 0xc000dd2c00}, {0x16ed9c0, 0xc000e98c00})
	/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/controller.go:273 +0xe2
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/shared_informer.go:785 +0xf7
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0000b6f38?, {0x1944860, 0xc0005a6030}, 0x1, 0xc000a7a060)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x31?, 0xc0000b6fb0?)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000206300)
	/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/shared_informer.go:781 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:71 +0x85
```

**Comment by VanillaSpoon** [comment]
https://github.com/project-codeflare/instascale/pull/96
